version: "3.9"

services:
  backend:
    container_name: super-loan.report-service
    build:
      context: ./main
    restart: unless-stopped
    ports:
      - "5002:4000"
    env_file:
      - .docker.env
    networks:
      - main-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 300M

networks:
  main-network:
    driver: bridge
