name: CI for Loan Service

on:
  push:
    branches:
      - develop
      - release
      - main
    paths:
      - "super-loan.loan-service/**"
  pull_request:
    branches:
      - develop
      - release
      - main
    paths:
      - "super-loan.loan-service/**"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.LOAN_SERVICE_DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.6.2"

      - name: Install dependencies
        run: |
          cd ./super-loan.loan-service/main 
          npm install

      - name: Run tests
        run: |
          cd ./super-loan.loan-service/main 
          npm run test

      - name: Test results
        if: failure()
        run: echo "Tests failed, cannot merge!"
